### PR TITLE
Redesign of All forms

### PR DESCRIPTION
**Pull request by kentnorca**
>Added Member list, create new member, Event list, create new event in main menu

### CODE REVIEW

**Comment by khrizthero24** [comment]
**Member List.cs**
- change picturebox1 size to 150,150
- change menustrip forecolor to white
- center listview1 to groupbox
- center guardian info groubox to member info groupbox

**DevMode.cs**
- change memberlist groupbox forecolor to white
- change menustrip forecolor to white
- change picturebox1 to a proper picture

**Event List.cs**
- FONT IS NOT CONSISTENT

**MainMenu.cs**
- change picture

**NewEvent.cs**
- change layout
- font not consistent

**New Member.cs**
- FONT NOT CONSISTENT
- textboxes are not in same height
- pls add more context (grouping name, address and shit)

**Review by TeaRX27 — DISMISSED** [review]
MainMenu.cs

**Review by TeaRX27 — CHANGES_REQUESTED** [review]
**MainMenu.cs**
- Make the Election Button Visible


the rest are same as the review from @khrizthero24

**Comment by khrizthero24** [comment]
Ok. Will check tomorrow for approval.

**Review by khrizthero24 — APPROVED** [review]
Good for merging. @TeaRX27  please confirm for merging.

**Pull request merged**
